import org.scalatest.funsuite.AnyFunSuite
import org.scalatest.matchers.should.Matchers._

class GcContentSpec extends AnyFunSuite {
  import GcContent._

  test("Count GC counts") {
    val in = "AGCTATAG"
    val actual = countGC(in)
    val expected = 37.5
    actual shouldBe expected
  }

  test("Count GC counts xzf") {
    val in = "AGTGACAGTGAGCATGCCACATCTGTATTTTAAGGCCATTCAGCTTACTACCGGGTACATTCAGGTCGAACTTCGGAAGGTAAGAGCACAATCCCCCCTCCGTCTTCATTTCATGCGTTGTGCGAGAGCCATCCATGGGCAGTAAGAGATAGAAAGGGCGACACAACCGTACGCAGTTCGGGTCACCTGGGACCGAAACTTTGCAAATGGCTGAATTGGATAAGAAGAGGCCTGTTCCCAAACCTTTTGGTATCTGGGAAACCTCTACGCACCTGGTAAAAGCATTCCATCAGGAGGTAACACCTCTCGTGTCAATCGCGATTGGTAAGGGGCATCCTTCCGCCCCTGGACATAATGTCTCATAGTCCACATCGGTCCGCAGACTGATGCGGTGGTTCTCTATCTCCGCGCGACCGCTTTAGCCTCGGTCTTCACTGCCCTTAGCATCACTCCACGCCGGGTTTTCCAAGCAACCCCACTAAAAAATATAAGATCATGACCGCCTAAGTAAGTCCCGTATGGGTAGCATGGATGAAGCTCCCTCTCATGGCAATCGCTCGATGTATCATGAGAGCCTGTATGCCCTTGGTGCGCATCTTGGCAGAATAGCGACACTGTCTGCATATGGCGTAATAACAAAAAAGTGGGGAATTTTATAAGCAAGGGGTCGTACATCCTCGTCCTAAATGTCTCAAGAAGAAATCTCTTTATCGTACGACGAAGTATAACATCACACGCCAATTTAGATGCGGTGAAGGGTGCATTGTTGACAAACTTGTTTACGTTCGGCTGTGACCTTC"
    val actual = countGC(in)
    val expected = 49.125
    actual shouldBe expected
  }

}
